package com.luannv.mf.enums;

public enum PermissionEnum {

	// ==== USER ====
	USER_VIEW,
	USER_DELETE,
	USER_MANAGE_SKILLS,
	USER_MANAGE_PORTFOLIO,

	// ==== PROJECT ====
	PROJECT_CREATE,
	PROJECT_VIEW,
	PROJECT_UPDATE,
	PROJECT_DELETE,
	ALL_PROJECTS,
	// freelancer
	FREELANCER_PROJECT_VIEW_ASSIGNED,
	// ==== PROPOSAL ==== updating
	PROPOSAL_CREATE,
	PROPOSAL_VIEW,
	PROPOSAL_UPDATE,
	PROPOSAL_DELETE,
	PROPOSAL_ACCEPT,
	PROPOSAL_REJECT,
	PROPOSAL_FILTER_BY_PROJECT,

	// ==== MILESTONE ==== updating
	MILESTONE_CREATE,
	MILESTONE_VIEW,
	MILESTONE_UPDATE,
	MILESTONE_DELETE,
	MILESTONE_SUBMIT,
	MILESTONE_APPROVE,
	MILESTONE_REQUEST_REVISION,
	MILESTONE_HANDLE_PAYMENT,

	// ==== REVIEW ==== updating
	REVIEW_CREATE,
	REVIEW_VIEW,
	REVIEW_FILTER,
	REVIEW_CALCULATE_RATING,

	// ==== MESSAGE ==== updating
	MESSAGE_SEND,
	MESSAGE_RECEIVE,
	MESSAGE_VIEW_HISTORY,
	MESSAGE_MARK_AS_READ,

	// ==== ADMIN ====
	ADMIN_USER_BAN,
	ADMIN_DASHBOARD_VIEW,
	ADMIN_STATISTICS_VIEW,
	ADMIN_USER_MANAGEMENT,
	ADMIN_PROJECT_MANAGEMENT,
	ADMIN_REVIEW_MANAGEMENT,
}
